import {
  ScannedMedicine,
  Prescription,
  SafetyFinding,
  LabReport,
  HealthEvent,
  DoctorQuestion,
  UserProfile,
  CareCircleMember,
} from '../types';

export const demoUser: UserProfile = {
  name: 'Shreya Chouhan',
  email: 'iamshreyachouhan@gmail.com',
  age: 42,
  signedInAt: '2026-10-07T10:00:00Z',
  allergies: ['Penicillin (mild rash)'],
  conditions: ['Type 2 Diabetes', 'Mild Hypertension'],
};

export const demoPrescription: Prescription = {
  id: 'rx-2026-0891',
  doctorName: 'Dr. Aris Thorne, MD',
  clinicOrHospital: 'St. Jude Integrated Cardiology & Internal Medicine',
  patientName: 'Shreya Chouhan',
  prescriptionDate: '08 Oct 2026',
  confidence: 'high',
  overallNotes: 'Monitor morning blood pressure. Maintain low-sodium diet. Take Metformin strictly with meals to minimize gastrointestinal discomfort.',
  items: [
    {
      id: 'rx-item-1',
      medicineName: 'Metformin Hydrochloride',
      genericName: 'Metformin HCl',
      dosage: '500 mg',
      frequency: 'Twice daily (1-0-1)',
      timing: 'Morning & Evening',
      duration: 'Ongoing (90 days supply)',
      instructions: 'Take with or immediately after meals',
      confidence: 'high',
      matchedMedicineId: 'med-demo-1',
      reconciliationStatus: 'matched',
    },
    {
      id: 'rx-item-2',
      medicineName: 'Lisinopril',
      genericName: 'Lisinopril',
      dosage: '10 mg',
      frequency: 'Once daily (1-0-0)',
      timing: 'Morning (08:00)',
      duration: 'Ongoing',
      instructions: 'Take in morning with a glass of water',
      confidence: 'high',
      matchedMedicineId: 'med-demo-2',
      reconciliationStatus: 'matched',
    },
    {
      id: 'rx-item-3',
      medicineName: 'Atorvastatin Calcium',
      genericName: 'Atorvastatin',
      dosage: '20 mg',
      frequency: 'Once daily at bedtime (0-0-0-1)',
      timing: 'Night (22:00)',
      duration: 'Ongoing',
      instructions: 'Take at night before sleep',
      confidence: 'high',
      matchedMedicineId: 'med-demo-3',
      reconciliationStatus: 'matched',
    },
    {
      id: 'rx-item-4',
      medicineName: 'Amoxicillin Oral Suspension / Capsule',
      genericName: 'Amoxicillin Trihydrate',
      dosage: '500 mg',
      frequency: 'Three times daily (1-1-1)',
      timing: 'Morning, Afternoon, Night',
      duration: '7 days',
      instructions: 'Complete full course if initiated after dental procedure',
      confidence: 'medium',
      matchedMedicineId: undefined,
      reconciliationStatus: 'needs_review',
    },
  ],
};

export const demoMedicines: ScannedMedicine[] = [
  {
    id: 'med-demo-1',
    medicineName: 'Glucophage 500mg (Metformin HCl)',
    genericName: 'Metformin Hydrochloride',
    activeIngredients: ['Metformin HCl 500mg'],
    category: 'ANTIDIABETIC',
    simpleExplanation: 'This medicine belongs to a group called biguanides. It helps your body respond normally to insulin and keeps blood sugar levels balanced.',
    simpleExplanationHi: 'यह दवा आपके शरीर में इंसुलिन की कार्यक्षमता बढ़ाकर रक्त शर्करा (ब्लड शुगर) को संतुलित रखने में मदद करती है।',
    generalUse: 'This medicine is generally used for blood sugar management in type 2 diabetes, commonly taken alongside meals to prevent stomach sensitivity.',
    generalUseHi: 'यह दवा आमतौर पर टाइप 2 डायबिटीज में ब्लड शुगर नियंत्रित करने के लिए दी जाती है, इसे पेट की सुरक्षा हेतु भोजन के साथ लिया जाता है।',
    strength: '500 mg',
    dosageForm: 'Film-coated oral tablet',
    manufacturer: 'Merck Healthcare',
    expiryDate: '10/2027',
    batchNumber: 'MET-89211',
    visibleInstructions: 'Take with meals twice daily. Swallow whole with water.',
    prescriptionInstruction: 'Take with or immediately after meals (Twice daily)',
    frequency: 'Twice daily',
    timing: 'Morning',
    foodInstruction: 'With breakfast and dinner',
    storageInstruction: 'Store below 25°C',
    confidence: 'high',
    evidence: ['GLUCOPHAGE', 'Metformin HCl 500mg', 'Merck', 'EXP 10/2027'],
    whatWeCouldVerify: ['Medicine name (Glucophage)', 'Active ingredient (Metformin HCl)', 'Strength (500 mg)', 'Oral tablet form', 'Expiry (10/2027)', 'Manufacturer (Merck)'],
    whatWeCouldntVerify: [],
    source: 'From medicine label & prescription',
    uncertainFields: [],
    needsReview: false,
    clinicalAdvisory: 'First-line therapy for glycemic control. Taking with food prevents stomach upset.',
    scannedAt: '08 Oct 2026 · 09:15',
    takenToday: true,
    takenAt: '08:12 AM',
    prescriptionId: 'rx-2026-0891',
    status: 'current',
  },
  {
    id: 'med-demo-2',
    medicineName: 'Prinivil 10mg (Lisinopril)',
    genericName: 'Lisinopril',
    activeIngredients: ['Lisinopril 10mg'],
    category: 'BLOOD PRESSURE MEDICINE',
    simpleExplanation: 'This medicine belongs to a family of medicines called ACE inhibitors. It helps blood vessels relax and widen, allowing blood to circulate with less effort.',
    simpleExplanationHi: 'यह दवा रक्त वाहिकाओं को शिथिल और चौड़ा करती है, जिससे हृदय आसानी से रक्त संचार कर पाता है।',
    generalUse: 'This medicine is generally used to lower elevated blood pressure (hypertension) and support overall cardiovascular and renal health.',
    generalUseHi: 'यह दवा आमतौर पर उच्च रक्तचाप को कम करने तथा हृदय व गुर्दे की सुरक्षा के लिए उपयोग की जाती है।',
    strength: '10 mg',
    dosageForm: 'Oral tablet',
    manufacturer: 'Merck & Co.',
    expiryDate: '03/2028',
    batchNumber: 'LIS-40192',
    visibleInstructions: 'Take once daily in morning. Do not chew.',
    prescriptionInstruction: 'Take in morning with a glass of water (Once daily)',
    frequency: 'Once daily',
    timing: 'Morning',
    foodInstruction: 'Can be taken with or without food',
    storageInstruction: 'Store in dry place away from moisture',
    confidence: 'high',
    evidence: ['PRINIVIL 10mg', 'Lisinopril', 'EXP 03/2028'],
    whatWeCouldVerify: ['Medicine name (Prinivil)', 'Active ingredient (Lisinopril)', 'Strength (10 mg)', 'Expiry (03/2028)', 'Manufacturer (Merck)'],
    whatWeCouldntVerify: [],
    source: 'From medicine label & prescription',
    uncertainFields: [],
    needsReview: false,
    clinicalAdvisory: 'ACE inhibitor for blood pressure protection. May cause dry cough in rare cases.',
    scannedAt: '08 Oct 2026 · 09:18',
    takenToday: true,
    takenAt: '08:15 AM',
    prescriptionId: 'rx-2026-0891',
    status: 'current',
  },
  {
    id: 'med-demo-3',
    medicineName: 'Lipitor 20mg (Atorvastatin)',
    genericName: 'Atorvastatin Calcium',
    activeIngredients: ['Atorvastatin 20mg'],
    category: 'CHOLESTEROL MEDICINE',
    simpleExplanation: 'This medicine belongs to a class called statins. It works inside the liver to decrease the formation of LDL ("bad") cholesterol and triglycerides.',
    simpleExplanationHi: 'यह दवा लिवर में खराब कोलेस्ट्रॉल (LDL) के निर्माण को कम करने में मदद करती है।',
    generalUse: 'This medicine is generally used to maintain healthy blood cholesterol levels and reduce long-term cardiovascular risks.',
    generalUseHi: 'यह दवा आमतौर पर रक्त में कोलेस्ट्रॉल की मात्रा को नियंत्रित करने और हृदय स्वास्थ्य को बनाए रखने के लिए दी जाती है।',
    strength: '20 mg',
    dosageForm: 'Film-coated tablet',
    manufacturer: 'Viatris / Pfizer',
    expiryDate: '11/2026',
    batchNumber: 'LIP-0912A',
    visibleInstructions: 'Take once daily at bedtime.',
    prescriptionInstruction: 'Take once daily at bedtime before sleep (0-0-0-1)',
    frequency: 'Once daily',
    timing: 'Night',
    foodInstruction: 'With or without food at bedtime',
    storageInstruction: 'Store at 20°C to 25°C',
    confidence: 'high',
    evidence: ['LIPITOR 20mg', 'Atorvastatin Calcium', 'EXP 11/2026'],
    whatWeCouldVerify: ['Medicine name (Lipitor)', 'Active ingredient (Atorvastatin Calcium)', 'Strength (20 mg)', 'Expiry (11/2026)'],
    whatWeCouldntVerify: ['Remaining pill count in bottle'],
    source: 'From medicine label & prescription',
    uncertainFields: [],
    needsReview: true,
    clinicalAdvisory: 'HMG-CoA reductase inhibitor for lipid management. Bottle expires within 28 days.',
    scannedAt: '08 Oct 2026 · 09:22',
    takenToday: false,
    prescriptionId: 'rx-2026-0891',
    status: 'expiring_soon',
  },
  {
    id: 'med-demo-4',
    medicineName: 'Advil 400mg (Ibuprofen)',
    genericName: 'Ibuprofen',
    activeIngredients: ['Ibuprofen 400mg'],
    category: 'PAIN RELIEVER',
    simpleExplanation: 'This medicine is a non-steroidal anti-inflammatory drug (NSAID). It works by temporarily calming chemical signals that cause pain, stiffness, and swelling.',
    simpleExplanationHi: 'यह एक दर्दनिवारक व सूजन रोधी दवा है जो दर्द और सूजन के संकेतों को शांत करती है।',
    generalUse: 'This medicine is generally used for temporary relief of mild to moderate aches, headaches, or inflammation.',
    generalUseHi: 'यह दवा आमतौर पर सिरदर्द, जोड़ों के दर्द, बुखार या सूजन से अस्थायी राहत पाने के लिए उपयोग की जाती है।',
    strength: '400 mg',
    dosageForm: 'Coated tablet / NSAID',
    manufacturer: 'Haleon',
    expiryDate: '08/2027',
    batchNumber: 'IBU-9943B',
    visibleInstructions: 'Take 1 tablet every 6 to 8 hours as needed for pain with full glass of water.',
    prescriptionInstruction: 'Not listed on Dr. Aris Thorne written prescription (Present in home cabinet)',
    frequency: 'As needed (PRN)',
    timing: 'As needed',
    foodInstruction: 'Always take with food or milk',
    storageInstruction: 'Store at room temperature',
    confidence: 'high',
    evidence: ['Advil 400mg', 'Ibuprofen Tablet', 'EXP 08/2027'],
    whatWeCouldVerify: ['Medicine name (Advil)', 'Active ingredient (Ibuprofen)', 'Strength (400 mg)', 'Expiry (08/2027)'],
    whatWeCouldntVerify: ['Prescription relationship (Not prescribed on current Rx)'],
    source: 'From medicine label (Cabinet only)',
    uncertainFields: [],
    needsReview: true,
    clinicalAdvisory: 'NSAID pain reliever. Not listed on Dr. Thorne prescription and interacts with Lisinopril.',
    scannedAt: '08 Oct 2026 · 09:26',
    takenToday: false,
    prescriptionId: undefined,
    status: 'needs_review',
  },
];

export const demoSafetyFindings: SafetyFinding[] = [
  {
    id: 'finding-1',
    level: 'review',
    title: 'Drug Interaction: Lisinopril + Ibuprofen',
    titleHi: 'दवाओं का टकराव: लिसिनोप्रिल + इबुप्रोफेन',
    description: 'Concurrent use of NSAIDs like Ibuprofen with ACE inhibitors like Lisinopril may attenuate the blood pressure lowering effect and increase renal stress.',
    descriptionHi: 'इबुप्रोफेन जैसी दर्दनिवारक दवा का लिसिनोप्रिल के साथ लगातार उपयोग ब्लड प्रेशर नियंत्रण को कम कर सकता है और गुर्दे पर दबाव डाल सकता है।',
    involvedMedicines: ['Prinivil 10mg (Lisinopril)', 'Advil 400mg (Ibuprofen)'],
    actionRecommendation: 'Discuss with Dr. Aris Thorne whether Paracetamol (Acetaminophen) can be used as a safer alternative for joint discomfort.',
    actionRecommendationHi: 'डॉ. थोर्न से परामर्श लें कि क्या दर्द के लिए पैरासिटामोल एक सुरक्षित विकल्प हो सकता है।',
    severity: 'moderate',
    ruleType: 'interaction',
  },
  {
    id: 'finding-2',
    level: 'review',
    title: 'Expiry Watch: Atorvastatin (Lipitor 20mg)',
    titleHi: 'समाप्ति चेतावनी: एटोरवास्टेटिन (Lipitor 20mg)',
    description: 'This medicine batch expires in November 2026 (approximately 28 days remaining). Active chemical potency may decline after expiry.',
    descriptionHi: 'यह दवा नवंबर 2026 में समाप्त हो रही है (लगभग 28 दिन शेष)। समाप्ति तिथि के बाद दवा का असर कम हो सकता है।',
    involvedMedicines: ['Lipitor 20mg (Atorvastatin)'],
    actionRecommendation: 'Request a fresh refill from your pharmacy during your upcoming clinic checkup.',
    actionRecommendationHi: 'अपनी अगली डॉक्टर विजिट के दौरान फार्मेसी से नया रिफिल प्राप्त करें।',
    severity: 'mild',
    ruleType: 'expiry',
  },
  {
    id: 'finding-3',
    level: 'review',
    title: 'Prescription Gap: Amoxicillin 500mg Unaccounted',
    titleHi: 'पर्चे का अंतर: एमोक्सिसिलिन 500mg उपलब्ध नहीं',
    description: 'Dr. Thorne prescribed Amoxicillin 500mg (7 days course), but it is not currently scanned into your active medicine box.',
    descriptionHi: 'डॉक्टर ने 7 दिनों के लिए एमोक्सिसिलिन 500mg लिखी थी, लेकिन यह आपकी सक्रिय दवाओं में स्कैन नहीं हुई है।',
    involvedMedicines: ['Amoxicillin 500mg'],
    actionRecommendation: 'Verify whether this course was already finished following your dental appointment or if it needs to be picked up.',
    actionRecommendationHi: 'जांचें कि क्या यह कोर्स पूरा हो चुका है या इसे फार्मेसी से लाना बाकी है।',
    severity: 'mild',
    ruleType: 'unverified_label',
  },
];

export const demoLabReport: LabReport = {
  id: 'lab-2026-104',
  reportName: 'Comprehensive Metabolic Panel & Glycemic Marker',
  labName: 'Quest Diagnostics · Metro Center',
  reportDate: '09 Oct 2026',
  patientName: 'Shreya Chouhan',
  summary: 'Overall renal function is stable. Glycemic index is mildly elevated (HbA1c 6.8%), consistent with managed Type 2 Diabetes.',
  parameters: [
    {
      parameterName: 'Hemoglobin A1c (HbA1c)',
      value: '6.8',
      unit: '%',
      referenceRange: '< 5.7% (Normal), 5.7 - 6.4% (Prediabetes)',
      status: 'borderline',
      simpleExplanation: '3-month average of blood glucose. Target for managed diabetes is generally under 7.0%.',
    },
    {
      parameterName: 'Estimated GFR (eGFR)',
      value: '88',
      unit: 'mL/min/1.73m²',
      referenceRange: '≥ 60 mL/min/1.73m²',
      status: 'normal',
      simpleExplanation: 'Shows that your kidneys are filtering efficiently and safely tolerating your blood pressure medication.',
    },
    {
      parameterName: 'Serum Creatinine',
      value: '0.92',
      unit: 'mg/dL',
      referenceRange: '0.59 - 1.04 mg/dL',
      status: 'normal',
      simpleExplanation: 'Standard waste product indicating healthy kidney clearance.',
    },
    {
      parameterName: 'Fasting Plasma Glucose',
      value: '124',
      unit: 'mg/dL',
      referenceRange: '70 - 99 mg/dL',
      status: 'borderline',
      simpleExplanation: 'Morning sugar level before breakfast. Supports continuing Metformin with meals.',
    },
    {
      parameterName: 'Blood Pressure (Clinic)',
      value: '128 / 82',
      unit: 'mmHg',
      referenceRange: '< 120/80 mmHg',
      status: 'normal',
      simpleExplanation: 'Well controlled on Lisinopril 10mg daily.',
    },
  ],
};

export const demoHealthEvents: HealthEvent[] = [
  {
    id: 'evt-1',
    date: '08 OCT 2026',
    time: '09:00',
    title: 'Prescription Scanned',
    titleHi: 'डॉक्टर का पर्चा स्कैन किया गया',
    description: 'Dr. Aris Thorne (Cardiology & Internal Medicine) prescription recorded with 4 prescribed drugs.',
    descriptionHi: 'डॉ. थोर्न का पर्चा रिकॉर्ड किया गया जिसमें 4 दवाएं शामिल हैं।',
    category: 'prescription',
    iconType: 'FileText',
  },
  {
    id: 'evt-2',
    date: '08 OCT 2026',
    time: '09:30',
    title: '4 Medicines Identified',
    titleHi: '4 दवाओं की पैकेजिंग की पहचान हुई',
    description: 'Metformin, Lisinopril, Atorvastatin, and Ibuprofen scanned and validated through Gemini multimodal vision.',
    descriptionHi: 'मल्टीमोडल विज़न के माध्यम से 4 दवाओं की पुष्टि की गई।',
    category: 'scan',
    iconType: 'Camera',
  },
  {
    id: 'evt-3',
    date: '08 OCT 2026',
    time: '09:45',
    title: 'Safety Radar Review Completed',
    titleHi: 'सुरक्षा समीक्षा पूरी हुई',
    description: 'Lisinopril + Ibuprofen interaction flagged. Atorvastatin 28-day expiry watch initiated.',
    descriptionHi: 'लिसिनोप्रिल और इबुप्रोफेन का टकराव चिन्हित हुआ। एटोरवास्टेटिन की समाप्ति 28 दिन में।',
    category: 'safety',
    iconType: 'ShieldAlert',
  },
  {
    id: 'evt-4',
    date: '09 OCT 2026',
    time: '14:20',
    title: 'Blood Report Linked',
    titleHi: 'रक्त जांच रिपोर्ट जोड़ी गई',
    description: 'Metabolic & Glycemic panel processed. eGFR 88 confirms good renal tolerance.',
    descriptionHi: 'मेटाबॉलिक पैनल रिपोर्ट दर्ज। eGFR 88 सामान्य गुर्दे के कार्य की पुष्टि करता है।',
    category: 'lab_report',
    iconType: 'Activity',
  },
  {
    id: 'evt-5',
    date: '12 OCT 2026',
    time: '11:00',
    title: 'Doctor Questions Prepared',
    titleHi: 'डॉक्टर विजिट के लिए सवाल तैयार',
    description: '4 synthesized questions ready for next follow-up consultation with Dr. Thorne.',
    descriptionHi: 'डॉ. थोर्न से परामर्श के लिए 4 महत्वपूर्ण प्रश्न तैयार किए गए।',
    category: 'appointment',
    iconType: 'HelpCircle',
  },
];

export const demoDoctorQuestions: DoctorQuestion[] = [
  {
    id: 'q-demo-1',
    category: 'Safety',
    question: 'Should I avoid taking Ibuprofen for joint discomfort while I am on Lisinopril 10mg?',
    questionHi: 'क्या लिसिनोप्रिल 10mg लेते समय जोड़ों के दर्द के लिए इबुप्रोफेन लेने से बचना चाहिए?',
    context: 'Sahaara flagged that NSAIDs like Ibuprofen can diminish Lisinopril’s blood pressure control and place added stress on kidneys.',
    contextHi: 'सहारा सुरक्षा इंजन ने पाया कि इबुप्रोफेन लिसिनोप्रिल के बीपी नियंत्रण प्रभाव को कम कर सकता है।',
    saved: true,
  },
  {
    id: 'q-demo-2',
    category: 'Duration',
    question: 'My current Atorvastatin (Lipitor 20mg) bottle expires next month in November 2026. Can I get a fresh refill now?',
    questionHi: 'मेरी एटोरवास्टेटिन की शीशी अगले महीने नवंबर में समाप्त हो रही है। क्या मुझे नया पर्चा/रिफिल मिल सकता है?',
    context: 'Active package reaches manufacturer expiry date in 28 days.',
    contextHi: 'दवा की वर्तमान शीशी 28 दिनों में समाप्त हो रही है।',
    saved: true,
  },
  {
    id: 'q-demo-3',
    category: 'Reconciliation',
    question: 'Do I still need to take the Amoxicillin 500mg course written on the prescription, or was that only for my past dental visit?',
    questionHi: 'क्या मुझे पर्चे में लिखी एमोक्सिसिलिन 500mg अभी भी लेनी है या वह केवल दंत चिकित्सा के लिए थी?',
    context: 'The prescription includes Amoxicillin TID for 7 days, but it is not currently in your active daily medicine box.',
    contextHi: 'पर्चे में 7 दिन का कोर्स दर्ज है लेकिन यह कैबिनेट में मौजूद नहीं है।',
    saved: true,
  },
  {
    id: 'q-demo-4',
    category: 'Timing',
    question: 'If I have breakfast later than usual on weekends, should I delay my morning Metformin dose to match the meal?',
    questionHi: 'यदि सप्ताहांत में नाश्ता देर से हो, तो क्या मेटफॉर्मिन की खुराक भी भोजन के समय तक टालनी चाहिए?',
    context: 'Metformin works best with food to reduce stomach sensitivity.',
    contextHi: 'पेट की परेशानी से बचने के लिए मेटफॉर्मिन भोजन के साथ लेना सर्वोत्तम है।',
    saved: true,
  },
];

export const demoCareCircleMembers: CareCircleMember[] = [
  {
    id: 'care-1',
    name: 'Rohit Chouhan',
    relation: 'Spouse',
    permissions: {
      schedule: true,
      medicines: true,
      reports: false,
      questions: true,
    },
    lastAccessed: 'Yesterday · 19:30',
  },
  {
    id: 'care-2',
    name: 'Ananya Chouhan',
    relation: 'Daughter',
    permissions: {
      schedule: true,
      medicines: true,
      reports: true,
      questions: true,
    },
    lastAccessed: '3 days ago',
  },
];
