import React from 'react';
import { Printer, X, Download, ShieldCheck, Heart } from 'lucide-react';
import {
  UserProfile,
  ScannedMedicine,
  Prescription,
  SafetyFinding,
  LabReport,
  DoctorQuestion,
} from '../modules/types';
import { useI18n } from '../modules/i18n/I18nContext';

interface AppointmentBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
  user: UserProfile | null;
  medicines: ScannedMedicine[];
  prescription: Prescription | null;
  findings: SafetyFinding[];
  reports: LabReport[];
  questions: DoctorQuestion[];
}

export const AppointmentBriefModal: React.FC<AppointmentBriefModalProps> = ({
  isOpen,
  onClose,
  user,
  medicines,
  prescription,
  findings,
  reports,
  questions,
}) => {
  const { t } = useI18n();

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      className="fixed inset-0 z-50 bg-black/55 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto"
      onClick={onClose}
    >
      <div
        className="bg-[#FCFBF7] dark:bg-[#1C201C] border border-[#E3DCCF] dark:border-[#363D34] rounded-2xl max-w-3xl w-full p-6 md:p-10 shadow-2xl flex flex-col gap-6 max-h-[90vh] overflow-y-auto my-auto print:max-h-none print:shadow-none print:border-none print:p-0 print:bg-white text-[#2F322E] dark:text-[#F3EFE8]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header with actions */}
        <div className="flex items-center justify-between pb-4 border-b border-[#E3DCCF] dark:border-[#363D34] print:hidden">
          <div className="flex items-center gap-2">
            <span className="font-bold tracking-wider text-[#5A7359] dark:text-[#95A895]">
              SAHAARA
            </span>
            <span className="text-xs text-[#6D716B] dark:text-[#BDC2B8]">· {t('appointment_brief_title')}</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-lg bg-[#5A7359] hover:bg-[#485D47] text-white text-xs font-medium flex items-center gap-2 cursor-pointer shadow-xs transition-colors"
            >
              <Printer className="w-4 h-4" />
              <span>{t('btn_print_export', 'Print / Save PDF')}</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-[#EEEAE1] dark:hover:bg-[#282C27] text-[#6D716B] dark:text-[#BDC2B8] cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Clinical Document Content (Printable) */}
        <div className="flex flex-col gap-6 text-[#2F322E] dark:text-[#F3EFE8]">
          {/* Clinic Header */}
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pb-4 border-b border-[#E3DCCF] dark:border-[#363D34]">
            <div>
              <h2 className="text-2xl font-serif font-medium">
                Patient Medication & Safety Summary
              </h2>
              <p className="text-xs text-[#6D716B] dark:text-[#BDC2B8] mt-1">
                Generated by Sahaara Clinical Safety Platform · Prepared for Physician Consultation
              </p>
            </div>
            <div className="text-right text-xs">
              <div className="font-bold text-[#2F322E] dark:text-[#F3EFE8]">
                Patient: {user?.name || 'Patient'}
              </div>
              <div className="text-[#6D716B] dark:text-[#BDC2B8]">
                Age: {user?.age || '42'} · Date: {new Date().toLocaleDateString('en-GB')}
              </div>
            </div>
          </div>

          {/* 1. Active Medicines */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#5A7359] dark:text-[#95A895] mb-2">
              1. Current Active Medications ({medicines.length})
            </h3>
            <div className="rounded-xl border border-[#E3DCCF] dark:border-[#363D34] overflow-hidden text-xs">
              <table className="w-full text-left">
                <thead className="bg-[#EEEAE1] dark:bg-[#282C27] text-[11px] font-semibold text-[#2F322E] dark:text-[#F3EFE8]">
                  <tr>
                    <th className="p-2.5">Medicine & Generic</th>
                    <th className="p-2.5">Category</th>
                    <th className="p-2.5">Strength</th>
                    <th className="p-2.5">Schedule</th>
                    <th className="p-2.5">Expiry</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#E3DCCF] dark:divide-[#363D34]">
                  {medicines.map((m) => (
                    <tr key={m.id} className="hover:bg-black/2">
                      <td className="p-2.5 font-medium">
                        {m.medicineName}
                        <div className="text-[10px] text-[#6D716B] dark:text-[#BDC2B8]">{m.genericName}</div>
                      </td>
                      <td className="p-2.5 text-[11px]">
                        <span className="px-1.5 py-0.5 rounded-sm bg-[#DCE5D9] dark:bg-[#242D23] text-[#5A7359] dark:text-[#95A895] font-bold text-[9px]">
                          {m.category || 'MEDICINE'}
                        </span>
                      </td>
                      <td className="p-2.5">{m.strength}</td>
                      <td className="p-2.5">
                        {m.timing} · {m.foodInstruction}
                      </td>
                      <td className="p-2.5 text-[11px] text-[#6D716B] dark:text-[#BDC2B8]">
                        {m.expiryDate || 'N/A'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* 2. Safety Findings & Interactions */}
          {findings.length > 0 && (
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-[#5A7359] dark:text-[#95A895] mb-2">
                2. Safety Radar & Drug Interaction Findings
              </h3>
              <div className="flex flex-col gap-2">
                {findings.map((f) => (
                  <div
                    key={f.id}
                    className="p-3 rounded-lg border border-[#E3DCCF] dark:border-[#363D34] bg-[#FCFBF7] dark:bg-[#222621] text-xs"
                  >
                    <div className="font-semibold text-[#2F322E] dark:text-[#F3EFE8] flex items-center justify-between">
                      <span>{f.title}</span>
                      <span className="text-[10px] text-[#CBA457] font-bold uppercase">
                        Severity: {f.severity}
                      </span>
                    </div>
                    <p className="text-[#6D716B] dark:text-[#BDC2B8] text-[11px] mt-1">
                      {f.description}
                    </p>
                    <div className="text-[11px] text-[#5A7359] dark:text-[#95A895] font-medium mt-1">
                      Recommended clinical review: {f.actionRecommendation}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 3. Questions for Physician */}
          {questions.length > 0 && (
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-[#5A7359] dark:text-[#95A895] mb-2">
                3. Prepared Consultation Questions ({questions.length})
              </h3>
              <ol className="list-decimal list-inside space-y-1.5 text-xs text-[#2F322E] dark:text-[#F3EFE8] p-3 rounded-xl border border-[#E3DCCF] dark:border-[#363D34] bg-[#FCFBF7] dark:bg-[#222621]">
                {questions.map((q) => (
                  <li key={q.id} className="leading-relaxed font-medium">
                    {q.question}
                  </li>
                ))}
              </ol>
            </div>
          )}

          {/* Disclaimer Footer */}
          <div className="pt-4 border-t border-[#E3DCCF] dark:border-[#363D34] text-[10px] text-[#92958F] dark:text-[#889083] leading-tight">
            Confidential Clinical Patient Document. Sahaara provides optical prescription verification and interaction analysis based on package labels. Physician judgment supersedes automated suggestions.
          </div>
        </div>
      </div>
    </div>
  );
};
